### ISSUE TITLE
Shear Animation not exported properly, SVG animation

### ISSUE THREAD

**Issue by irwant** [friction2d/friction#221]
this is need fix for exported SVG animation. when i have keyframe value on x and y value shear transform, that just show animation at y value only. i have seen the svg code, the x value is there, just need the close tag `</g>`

**Comment by rodlie** [comment]
I can replicate skewX don't work if skewY has animation, but looking at the SVG code I see no issue.

>  just need the close tag </g>

Please provide more info.

**Comment by irwant** [comment]
sorry, that need tag `<g>` not close tag `</g>`

add tag `<g>` above code skewY, and skewX animation will work
![Screenshot_2024-08-15_15-02-25](https://github.com/user-attachments/assets/54d7aed0-630d-4e76-a6f7-adc3da0d5c6b)

**Comment by rodlie** [comment]
Ok, understand the problem.

But, fixing it with a group still does not seem to work properly, at least not with my tests (a rectangle, change skew X/Y, result is not expected).

**Comment by rodlie** [comment]
I think I have a fix, output (first is X, second is Y, third is both):
![skewXY](https://github.com/user-attachments/assets/e0173d9d-206c-4a5b-8150-45033aa1a690)

**Comment by rodlie** [comment]
Test builds: https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-skew/

Project file used to test:
[skew.friction.zip](https://github.com/user-attachments/files/16627791/skew.friction.zip)

**Comment by irwant** [comment]
Awesome, that work. 
and also work fine for my old project using enve. I using skew transform to get perspective. 
BTW there are is another problem, I don't know i must calling it bug or that not implemented. 
so when i need masking for the shape, i am always edited the SVG code using tag `<mask>`. I am using masking than clip-path because masking support with animation. Thank you for fix it.

**Comment by rodlie** [comment]
Great :+1: 

> BTW there are is another problem, I don't know i must calling it bug or that not implemented.
so when i need masking for the shape, i am always edited the SVG code using tag <mask>. I am using masking than clip-path because masking support with animation

Please create a new issue for this one (sounds like something that is not implemented), I also need a bit more info to work with as I'm unsure what to do :smile: Example files work best (what Friction exports and what you expect).

I can take a look at the new issue tomorrow after work (it's bedtime here).

Closing this as completed.
