### ISSUE TITLE
[Issue] Muting videos not persistent after saving

### ISSUE THREAD

**Issue by KirbysDarkNebula** [friction2d/friction#331]
Platform: Linux (using X11), Appimg, version 1.0.0-beta1 
Audio from videos doesn't save its "mute" property to the project, so every time you reopen a project all muted videos are unmuted.
This is not the case for normal audio files, as these maintain their mute after saving.
Steps to reproduce:
- Create project
- Add video with audio to timeline/viewport
- Mute the video through the speaker icon
- Save project
- Reopen project
- Video is now unmuted

**Comment by rodlie** [comment]
It's all just visibility state in the backend, looking at the code it does load and save visibility state. Will take a look at the issue when I get the time.

**Comment by rodlie** [comment]
Interesting...

```
setVisible "sound" true false
setVisible "sound" false false
addCacheHandler "WHATEVER.mp4"
setVisible "sound" false true
```

So, on project load the sound visibility is set three times (joy! :smile: ), the first time is correct, the second time is ignored (since it's the same), but when the cache handler for the video is added the audio is set to true (regardless if the video is visible or not).

Yeah... a bug.

**Comment by rodlie** [comment]
And the problem is... :drum: ... https://github.com/friction2d/friction/blob/main/src/core/Boxes/videobox.cpp#L188

This is just stupid IMHO. But I need to test that this does not break something else (stupid), as things tend to do :smile: 

Don't ask me why, this was done in enve by the prior maintainer.

**Comment by KirbysDarkNebula** [comment]
After testing some more it seems as if the mute property gets loaded perfectly now BUT when importing videos (that is, adding to the timeline or bringing from the asset tab) they're muted by default, so it seems like there should be some check in place for whether the media was just imported or loaded from project files.

**Comment by KirbysDarkNebula** [comment]
That fixed it, awesome!
