### ISSUE TITLE
Pixelized icons on HiDPI displays

### ISSUE THREAD

**Issue by prokoudine** [friction2d/friction#91]
According to #3, the program generates PNG images from SVG and then loads them. Unfortunately, it doesn't look like pixel density is taken into consideration when doing so. So on HiDPI displays icons look pixelized. Essentially, low-resolution icons get blown up to fit their containers.

![image](https://github.com/friction2d/friction/assets/57467/7b860506-e979-4d5b-a4b6-75fd0daaae33)

**Comment by rodlie** [comment]
This is a Qt issue IMHO, I supply an icon-theme (with all sizes) and use QIcon::fromTheme, what icon size Qt picks I don't know.

**Comment by rodlie** [comment]
One possible solution would be to supply only one (large) icon size in the icon theme, it should in theory look good with HiDPI and be scaled down on regular scaling?

**Comment by rodlie** [comment]
So, the issue was easier than I thought. We have to say to Qt that we want hidpi pixmaps for QIcons.
![friction-icon-hidpi](https://github.com/friction2d/friction/assets/34516798/0c87b334-6bf5-4b80-9bc5-140f184b26fe)

Note that this only works where we use QIcon. The timeline and properties still uses pixmap functions from enve (does not support hidpi).

So, issue #3 must be completed before all icons are hidpi-aware.
